### ISSUE TITLE
feat(elm): Change question when unanswered for certain period of time

### ISSUE THREAD

**Issue by pmrukot** [forcecraft/aion#108]
**Type**
Feature

**Current behaviour**
Question will not change when unanswered

**Expected behaviour**
Question should change if no one in the room knows the answer. Also appropriate notification should be shown.

**Comment by mrapacz** [comment]
![giphy 16](https://user-images.githubusercontent.com/15965147/30248207-b35f4640-9623-11e7-8485-969a5b73304e.gif)

**Comment by mrapacz** [comment]
My idea for the solution would be to send a timeout message everytime we change a question. Say, someone enters the room, they are presented with a question. This is when we command Elixir to send a message to the room after e.g. 10 seconds. Receiving this message would trigger change of the question in the room. 

This timer would be set every time a question changes (first person enters the room or someone answers the question correctly). 

In order to make this work we would need to:
 - either store timestamps saying when the question was set. It's possible that we would end up with a bunch of timers firing for the question that was already answered, before changing the question we could verify that the time delta is actually greater or equal than our timeout
 - or store timers and whenever we set a new timer we would have to cancel any other existing timers for a specific room. I'm not sure about this one, though, we may end up with some race condition related problems here, trying to cancel timers that have already started sending messages etc.

In both cases, storing additional data may be handled by an Agent or we can update the socket with this information. I'm actually for the first option. I would try to stick to storing actual data in the socket structure and in case we have to deal with this kind of metadata I would store it elsewhere in Agents. 

@pmrukot @jtkpiotr 
Let me know what you think, feel free to ask questions. I think we need to plan this thing well, since a big part of logic will later base its actions on these changes.

You can check the docs here:
 - [send_after](https://hexdocs.pm/elixir/Process.html#send_after/3)
 - [cancelling timers](https://hexdocs.pm/elixir/Process.html#cancel_timer/1)
 - [OTP Agents](https://elixir-lang.org/getting-started/mix-otp/agent.html)

**Comment by pmrukot** [comment]
Good read, first option and using agents seems like a good start.
